#!/bin/bash





~/bin/randrs

xsetroot -solid grey15

xscreensaver &

xrdb -merge .Xdefaults

gnome-keyring-daemon --replace --components=secrets,ssh,pcks11

SSH_ASKPASS=/usr/lib/ssh/x11-ssh-askpass ssh-add  < /dev/null

/usr/bin/trayer --edge top --width 15 --SetDockType true --align left --SetPartialStrut true & 
